### Criar uma UF
POST http://localhost:3000/uf
Content-Type: application/json

{
  "sigla": "SP",
  "nome": "São Paulo"
}

### Listar UFs
GET http://localhost:3000/uf

### Buscar UF por ID
GET http://localhost:3000/uf/1

### Atualizar UF
PUT http://localhost:3000/uf/1
Content-Type: application/json

{
  "sigla": "MG",
  "nome": "Minas Gerais"
}

### Remover UF
DELETE http://localhost:3000/uf/1